//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reddit.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Reddit.Core.Resources.AppStrings", typeof(AppStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Auth_Welcome {
            get {
                return ResourceManager.GetString("Auth_Welcome", resourceCulture);
            }
        }
        
        internal static string Auth_Title {
            get {
                return ResourceManager.GetString("Auth_Title", resourceCulture);
            }
        }
        
        internal static string Auth_Subtitle {
            get {
                return ResourceManager.GetString("Auth_Subtitle", resourceCulture);
            }
        }
        
        internal static string Auth_LoginInfo {
            get {
                return ResourceManager.GetString("Auth_LoginInfo", resourceCulture);
            }
        }
        
        internal static string Auth_Login {
            get {
                return ResourceManager.GetString("Auth_Login", resourceCulture);
            }
        }
        
        internal static string Auth_Password {
            get {
                return ResourceManager.GetString("Auth_Password", resourceCulture);
            }
        }
        
        internal static string Auth_LoginHint {
            get {
                return ResourceManager.GetString("Auth_LoginHint", resourceCulture);
            }
        }
        
        internal static string Auth_PasswordHint {
            get {
                return ResourceManager.GetString("Auth_PasswordHint", resourceCulture);
            }
        }
        
        internal static string Auth_LoginError {
            get {
                return ResourceManager.GetString("Auth_LoginError", resourceCulture);
            }
        }
        
        internal static string Auth_PasswordError {
            get {
                return ResourceManager.GetString("Auth_PasswordError", resourceCulture);
            }
        }
        
        internal static string Feed_PostedByText {
            get {
                return ResourceManager.GetString("Feed_PostedByText", resourceCulture);
            }
        }
        
        internal static string Feed_AwardsText {
            get {
                return ResourceManager.GetString("Feed_AwardsText", resourceCulture);
            }
        }
        
        internal static string Feed_CreatedAgo {
            get {
                return ResourceManager.GetString("Feed_CreatedAgo", resourceCulture);
            }
        }
        
        internal static string Feed_HomeTitle {
            get {
                return ResourceManager.GetString("Feed_HomeTitle", resourceCulture);
            }
        }
    }
}
